### ISSUE TITLE
Gorilla Mux not working on RaspberryPi with Go 1.15.x

### ISSUE THREAD

**Issue by DavideDA** [gorilla/mux#606]
Hello.
I recently updated my Go library from v1.14.x to v1.15.3 in my Raspberry Pi 4.
All my projects using Gorilla Mux have stopped from working!
I always used Linux/ARMv6 versions of Go (not officially ported for Raspberry, I think) and until v1.14.x they worked.
You can test my issue with this simple piece of code:

```
package main

import (
	"net/http"
	"log"
	"github.com/gorilla/mux"
)

func main() {
	router := mux.NewRouter()
	log.Fatal(http.ListenAndServe(":12111", router))
}
```

Running `go run main.go` you obtain this error message:
```
# vendor/golang.org/x/crypto/poly1305
/home/pi/go/src/vendor/golang.org/x/crypto/poly1305/sum_noasm.go:10:7: undefined: newMAC
```

What's happening?

Thank you, regards.

**Comment by DavideDA** [comment]
Resolved in Go version 1.15.6
